language: c
os:
    - linux

dist: bionic

install:
    - sudo apt-get -y install make gcc-arm-none-eabi libnewlib-arm-none-eabi
    - sudo apt-get -y install gcc-avr avr-libc

jobs:
    include:
    - compiler: arm-none-eabi-gcc
      env: BOARD=stm32_demo
    - compiler: arm-none-eabi-gcc
      env: BOARD=nrf52_demo
    - compiler: avr-gcc
      env: BOARD=arduino_v1

script:
    - make

